import type { ResumeTemplateTheme } from "./shared";

const singleColumnOrder = [
  "summary",
  "skills",
  "experience",
  "education",
  "certifications",
  "projects",
  "achievements",
  "languages",
  "strengths",
  "hobbies",
  "custom",
] as const;

const experiencedMainSections = [
  "summary",
  "experience",
  "education",
  "projects",
  "achievements",
  "custom",
] as const;

const sidebarSkillsFirst = ["skills", "certifications", "languages", "strengths", "hobbies"] as const;
const sidebarInfoFirst = ["languages", "certifications", "skills", "strengths", "hobbies"] as const;
const sidebarPersonalFirst = ["skills", "languages", "strengths", "hobbies", "references"] as const;

export const templateThemes: Record<number, ResumeTemplateTheme> = {
  1: {
    name: "Clean Single Column",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "underline",
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#4B5563",
      accent: "#2E5C8A",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D6DEE8",
      headerBg: "#FFFFFF",
    },
    pagePadding: "30px 36px",
    sectionSpacing: 22,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  2: {
    name: "Corporate Sidebar Blue",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "bar",
    fontFamily: "Lato, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5B6776",
      accent: "#4F8FCF",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D9E2EC",
      sidebarBg: "#2E5C8A",
      sidebarText: "#FFFFFF",
      sidebarMutedText: "#E4EDF5",
      sidebarBorder: "#5F7FA0",
      sidebarAccentSoft: "#4F8FCF",
    },
    sidebarWidth: "30%",
    sidebarSections: [...sidebarSkillsFirst],
    mainSections: [...experiencedMainSections],
    sectionSpacing: 20,
    headerDivider: true,
  },
  3: {
    name: "Colored Heading Corporate",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "bar",
    fontFamily: "Source Sans Pro, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#596579",
      accent: "#38BDF8",
      accentSoft: "#F8FAFC",
      accentText: "#111827",
      border: "#D8E3EC",
      headerBg: "#FFFFFF",
      nameText: "#1F2937",
      headingText: "#111827",
    },
    pagePadding: "30px 34px",
    sectionSpacing: 20,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  4: {
    name: "Left Accent Teal",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "accent",
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#52606D",
      accent: "#147D64",
      accentSoft: "#F9FAFB",
      accentText: "#FFFFFF",
      border: "#D9E3DE",
    },
    leftAccentLine: true,
    pagePadding: "30px 34px 30px 42px",
    sectionSpacing: 20,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  5: {
    name: "Premium Gray Sidebar",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "underline",
    fontFamily: "Lato, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5A6572",
      accent: "#374151",
      accentSoft: "#F5F5F5",
      accentText: "#FFFFFF",
      border: "#D7DEE8",
      sidebarBg: "#F5F5F5",
      sidebarText: "#1F2937",
      sidebarMutedText: "#5A6572",
      sidebarBorder: "#D6DCE4",
      sidebarAccentSoft: "#E8EBF0",
    },
    sidebarWidth: "31%",
    sidebarSections: [...sidebarInfoFirst],
    mainSections: [...experiencedMainSections],
    sectionSpacing: 20,
    headerDivider: true,
  },
  6: {
    name: "Professional Sidebar Teal",
    layout: "two-column",
    headerLayout: "stacked",
    headingStyle: "underline",
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#2E4A56",
      accentSoft: "#F9FAFB",
      accentText: "#111827",
      border: "#D8DEE5",
      sidebarBg: "#344E5C",
      sidebarText: "#FFFFFF",
      sidebarMutedText: "#D7E2E8",
      sidebarBorder: "#718793",
      sidebarAccentSoft: "#344E5C",
      nameText: "#1F2937",
      titleText: "#6B7280",
      headingText: "#111827",
      divider: "#8AA0AA",
    },
    sidebarWidth: "220px",
    sidebarPadding: "120px 20px 40px 20px",
    mainPadding: "45px 35px 35px 30px",
    sidebarSections: [],
    mainSections: [
      "summary",
      "skills",
      "experience",
      "projects",
      "education",
      "certifications",
      "languages",
      "strengths",
      "hobbies",
    ],
    fresherMainSections: [
      "summary",
      "skills",
      "education",
      "achievements",
      "certifications",
      "languages",
      "strengths",
      "hobbies",
      "experience",
      "projects",
    ],
    sectionSpacing: 12,
    headerDivider: false,
    summaryStyle: "plain",
    sidebarMode: "contact-only",
    sidebarHeading: "Contact",
    showHeaderContact: false,
  },
  7: {
    name: "Muted Coral Corporate",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "bar",
    fontFamily: "Source Sans Pro, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B6671",
      accent: "#E85D75",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E8D6DB",
      headerBg: "#FFFFFF",
    },
    topAccentBar: true,
    pagePadding: "30px 34px",
    sectionSpacing: 20,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  8: {
    name: "Compact ATS Single",
    layout: "single",
    headerLayout: "split",
    headingStyle: "underline",
    fontFamily: "Open Sans, Inter, sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#617084",
      accent: "#2E5C8A",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D8E1EB",
      headerBg: "#FFFFFF",
    },
    pagePadding: "26px 30px",
    sectionSpacing: 16,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  9: {
    name: "Premium Charcoal Sidebar",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "accent",
    fontFamily: "Lato, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#65727F",
      accent: "#374151",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D8DEE5",
      sidebarBg: "#374151",
      sidebarText: "#FFFFFF",
      sidebarMutedText: "#E5E7EB",
      sidebarBorder: "#6B7280",
      sidebarAccentSoft: "#4B5563",
    },
    sidebarWidth: "30%",
    sidebarSections: [...sidebarPersonalFirst],
    mainSections: [...experiencedMainSections],
    sectionSpacing: 20,
  },
  10: {
    name: "Blue Heading Corporate",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "bar",
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#657681",
      accent: "#2E5C8A",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D8E4E7",
      headerBg: "#FFFFFF",
    },
    topAccentBar: true,
    pagePadding: "30px 34px",
    sectionSpacing: 20,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  11: {
    name: "Classic Two Column",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "underline",
    fontFamily: "Georgia, Merriweather, serif",
    palette: {
      page: "#FFFFFF",
      text: "#253140",
      mutedText: "#657180",
      accent: "#2E5C8A",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D7DEE7",
      sidebarBg: "#EEF2F7",
      sidebarText: "#253140",
      sidebarMutedText: "#5D6D80",
      sidebarBorder: "#D7DEE7",
      sidebarAccentSoft: "#E5EBF2",
    },
    sidebarWidth: "31%",
    sidebarSections: [...sidebarInfoFirst],
    mainSections: [...experiencedMainSections],
    sectionSpacing: 22,
  },
  12: {
    name: "Soft Green Corporate",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "bar",
    fontFamily: "Lato, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#66736F",
      accent: "#147D64",
      accentSoft: "#F9FAFB",
      accentText: "#FFFFFF",
      border: "#D8E4DE",
      headerBg: "#FFFFFF",
    },
    pagePadding: "30px 34px",
    sectionSpacing: 20,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  13: {
    name: "Rose Sidebar Corporate",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "bar",
    fontFamily: "Source Sans Pro, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#2A2F37",
      mutedText: "#706A74",
      accent: "#E85D75",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E7D9DF",
      sidebarBg: "#F8FAFC",
      sidebarText: "#2A2F37",
      sidebarMutedText: "#706A74",
      sidebarBorder: "#E7D9DF",
      sidebarAccentSoft: "#E85D75",
    },
    sidebarWidth: "29%",
    sidebarSections: [...sidebarPersonalFirst],
    mainSections: [...experiencedMainSections],
    sectionSpacing: 20,
  },
  14: {
    name: "Minimal Left Accent",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "accent",
    fontFamily: "Merriweather, Georgia, serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5F6E7F",
      accent: "#D97706",
      accentSoft: "#FAFAFA",
      accentText: "#FFFFFF",
      border: "#E6DDD4",
    },
    leftAccentLine: true,
    pagePadding: "30px 34px 30px 42px",
    sectionSpacing: 20,
    headerDivider: true,
    mainSections: [...singleColumnOrder],
  },
  15: {
    name: "Corporate Clean",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "underline",
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#647081",
      accent: "#374151",
      accentSoft: "#F5F5F5",
      accentText: "#FFFFFF",
      border: "#D7DFE7",
      sidebarBg: "#F5F5F5",
      sidebarText: "#1F2937",
      sidebarMutedText: "#5F6C7A",
      sidebarBorder: "#D7DFE7",
      sidebarAccentSoft: "#E5E7EB",
    },
    sidebarWidth: "30%",
    sidebarSections: [...sidebarSkillsFirst],
    mainSections: [...experiencedMainSections],
    sectionSpacing: 20,
  },
};
