import type { ResumeTemplateTheme } from "./shared";

const singleColumnOrder = [
  "summary",
  "skills",
  "experience",
  "education",
  "certifications",
  "projects",
  "achievements",
  "languages",
  "strengths",
  "hobbies",
  "custom",
] as const;

const experiencedMainSections = [
  "summary",
  "experience",
  "education",
  "projects",
  "achievements",
  "custom",
] as const;

const sidebarSkillsFirst = ["skills", "certifications", "languages", "strengths", "hobbies"] as const;
const sidebarInfoFirst = ["languages", "certifications", "skills", "strengths", "hobbies"] as const;
const sidebarPersonalFirst = ["skills", "languages", "strengths", "hobbies", "references"] as const;

export const template1Theme: ResumeTemplateTheme = {
  name: "Clean Single Column",
  layout: "single",
  headerLayout: "split",
  headingStyle: "bar",
  layoutType: "single-column",
  headingVariant: "full-width-bar",
  typographyScale: 1.15,
  spacingScale: 1,
  fontFamily: "Inter, 'Open Sans', sans-serif",
  palette: {
    page: "#FFFFFF",
    text: "#222222",
    mutedText: "#666666",
    accent: "#F58200",
    accentSoft: "#FDF7F0",
    accentText: "#111827",
    headingText: "#111827",
    border: "#E5E7EB",
    headerBg: "#FFFFFF",
    nameText: "#222222",
    titleText: "#666666",
  },
  pagePadding: "36px 48px",
  headingInset: true,
  sectionSpacing: 14,
  headerDivider: true,
  showHeaderContact: true,
  summaryStyle: "plain",
  mainSections: [...singleColumnOrder],
};

export const templateThemes: Record<number, ResumeTemplateTheme> = {
  1: template1Theme,

  // ===== CATEGORY 1: MINIMAL PROFESSIONAL =====

  2: {
    // Template 2: Minimal Clean Blue
    name: "Minimal Clean Blue",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "underline",
    layoutType: "single-column",
    headingVariant: "underline",
    typographyScale: 1.0,
    spacingScale: 0.98,
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#2563EB",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      headerBg: "#FFFFFF",
      nameText: "#1F2937",
      headingText: "#1F2937",
    },
    pagePadding: "36px 40px",
    sectionSpacing: 18,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "education",
      "certifications",
      "projects",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  3: {
    // Template 3: Minimal Elegant Teal
    name: "Minimal Elegant Teal",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "accent",
    layoutType: "single-column",
    headingVariant: "label-bar",
    typographyScale: 0.98,
    spacingScale: 0.98,
    fontFamily: "Inter, 'Segoe UI', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#0D9488",
      accentSoft: "#F0FDF4",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
    },
    leftAccentLine: true,
    pagePadding: "36px 40px",
    sectionSpacing: 18,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "education",
      "certifications",
      "projects",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  4: {
    // Template 4: Minimal Professional Gray
    name: "Minimal Professional Gray",
    layout: "single",
    headerLayout: "split",
    headingStyle: "underline",
    layoutType: "single-column",
    headingVariant: "underline",
    typographyScale: 0.95,
    spacingScale: 0.95,
    fontFamily: "Inter, Arial, Helvetica, sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#374151",
      accentSoft: "#F9FAFB",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      headerBg: "#FFFFFF",
    },
    pagePadding: "32px 36px",
    sectionSpacing: 16,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "education",
      "certifications",
      "projects",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  // ===== CATEGORY 2: MODERN PROFESSIONAL =====

  5: {
    // Template 5: Modern Professional Navy
    name: "Modern Professional Navy",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "bar",
    layoutType: "sidebar",
    headingVariant: "full-width-bar",
    typographyScale: 1.02,
    spacingScale: 1.02,
    fontFamily: "Inter, 'Source Sans Pro', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5B6776",
      accent: "#1E293B",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      sidebarBg: "#F5F5F5",
      sidebarText: "#1F2937",
      sidebarMutedText: "#6B7280",
      sidebarBorder: "#E0E0E0",
      sidebarAccentSoft: "#EBEBEB",
    },
    sidebarWidth: "32%",
    sidebarSections: ["languages", "certifications", "skills", "strengths", "hobbies"],
    mainSections: [
      "summary",
      "experience",
      "education",
      "projects",
      "achievements",
      "custom",
    ],
    sidebarPadding: "24px 18px",
    sectionSpacing: 18,
    headerDivider: true,
    summaryStyle: "boxed",
  },

  // ===== CATEGORY 3: EXECUTIVE =====

  6: {
    // Template 6: Executive Sophisticate
    name: "Executive Sophisticate",
    layout: "two-column",
    headerLayout: "stacked",
    headingStyle: "underline",
    layoutType: "sidebar",
    headingVariant: "plain",
    typographyScale: 1.02,
    spacingScale: 1.02,
    fontFamily: "Lora, 'Times New Roman', serif",
    palette: {
      page: "#FFFFFF",
      text: "#111827",
      mutedText: "#475569",
      accent: "#0F4B78",
      accentSoft: "#F5F5F5",
      accentText: "#FFFFFF",
      border: "#CBD5E1",
      sidebarBg: "#143A5B",
      sidebarText: "#FFFFFF",
      sidebarMutedText: "#D7E2F0",
      sidebarBorder: "#1F4E7A",
      sidebarAccentSoft: "#1D4A78",
      nameText: "#111827",
      titleText: "#0F4B78",
      headingText: "#111827",
      divider: "#D9E4F2",
    },
    sidebarWidth: "31%",
    sidebarPadding: "32px 24px 32px 24px",
    mainPadding: "42px 36px 36px 34px",
    sidebarSections: [],
    mainSections: [
      "summary",
      "skills",
      "education",
      "experience",
      "projects",
      "certifications",
      "achievements",
      "languages",
    ],
    sectionSpacing: 16,
    headerDivider: true,
    summaryStyle: "plain",
    sidebarMode: "contact-only",
    sidebarHeading: "Contact",
    showHeaderContact: false,
  },

  // ===== CATEGORY 4: CREATIVE PROFESSIONAL =====

  7: {
    // Template 7: Creative Modern Rose
    name: "Creative Modern Rose",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "bar",
    layoutType: "single-column",
    headingVariant: "full-width-bar",
    typographyScale: 1.0,
    spacingScale: 1.0,
    fontFamily: "Poppins, Inter, sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#DC2626",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      headerBg: "#FFFFFF",
    },
    topAccentBar: true,
    pagePadding: "36px 42px",
    sectionSpacing: 18,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "projects",
      "education",
      "certifications",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  // ===== CATEGORY 5: COMPACT ATS =====

  8: {
    // Template 8: Compact ATS Optimized
    name: "Compact ATS Optimized",
    layout: "single",
    headerLayout: "split",
    headingStyle: "underline",
    layoutType: "single-column",
    headingVariant: "underline",
    typographyScale: 0.95,
    spacingScale: 0.95,
    fontFamily: "Inter, Arial, Helvetica, sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#2D3748",
      accentSoft: "#F9FAFB",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      headerBg: "#FFFFFF",
    },
    pagePadding: "32px 36px",
    sectionSpacing: 14,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "education",
      "certifications",
      "projects",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  // ===== CATEGORY 4: CREATIVE PROFESSIONAL =====

  9: {
    // Template 9: Creative Professional Charcoal
    name: "Creative Professional Charcoal",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "accent",
    layoutType: "sidebar",
    headingVariant: "label-bar",
    typographyScale: 1.0,
    spacingScale: 1.0,
    fontFamily: "Plus Jakarta Sans, Inter, sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5A6572",
      accent: "#7C3AED",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      sidebarBg: "#2D3748",
      sidebarText: "#FFFFFF",
      sidebarMutedText: "#E5E7EB",
      sidebarBorder: "#4B5563",
      sidebarAccentSoft: "#6B7280",
    },
    sidebarWidth: "30%",
    sidebarSections: ["skills", "languages", "strengths", "hobbies", "references"],
    mainSections: [
      "summary",
      "experience",
      "projects",
      "education",
      "certifications",
      "achievements",
      "custom",
    ],
    sectionSpacing: 18,
    headerDivider: true,
    summaryStyle: "boxed",
  },

  // ===== CATEGORY 2: MODERN PROFESSIONAL =====

  10: {
    // Template 10: Modern Teal Sidebar
    name: "Modern Teal Sidebar",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "underline",
    layoutType: "sidebar",
    headingVariant: "underline",
    typographyScale: 1.0,
    spacingScale: 1.0,
    fontFamily: "Inter, 'Open Sans', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5A6572",
      accent: "#0D9488",
      accentSoft: "#F0FDF4",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      sidebarBg: "#F8FAFB",
      sidebarText: "#1F2937",
      sidebarMutedText: "#6B7280",
      sidebarBorder: "#E5E7EB",
      sidebarAccentSoft: "#CCFBF1",
    },
    sidebarWidth: "30%",
    sidebarSections: ["languages", "certifications", "skills", "strengths", "hobbies"],
    mainSections: [
      "summary",
      "experience",
      "education",
      "projects",
      "achievements",
      "custom",
    ],
    sidebarPadding: "24px 16px",
    sectionSpacing: 16,
    headerDivider: true,
  },

  // ===== CATEGORY 3: EXECUTIVE =====

  11: {
    // Template 11: Executive Premium Serif
    name: "Executive Premium Serif",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "underline",
    layoutType: "sidebar",
    headingVariant: "underline",
    typographyScale: 1.05,
    spacingScale: 1.05,
    fontFamily: "Merriweather, 'Georgia', serif",
    palette: {
      page: "#FFFFFF",
      text: "#253140",
      mutedText: "#5A6572",
      accent: "#1E293B",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#D7DEE7",
      sidebarBg: "#F5F5F5",
      sidebarText: "#1F2937",
      sidebarMutedText: "#5A6572",
      sidebarBorder: "#E5E7EB",
      sidebarAccentSoft: "#F0F0F0",
    },
    sidebarWidth: "31%",
    sidebarSections: ["languages", "certifications", "skills", "strengths", "hobbies"],
    mainSections: [
      "summary",
      "experience",
      "education",
      "projects",
      "achievements",
      "custom",
    ],
    sectionSpacing: 20,
    headerDivider: true,
    summaryStyle: "boxed",
  },

  // ===== CATEGORY 2: MODERN PROFESSIONAL =====

  12: {
    // Template 12: Modern Emerald
    name: "Modern Emerald",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "bar",
    layoutType: "single-column",
    headingVariant: "full-width-bar",
    typographyScale: 1.02,
    spacingScale: 1.02,
    fontFamily: "Inter, 'Source Sans Pro', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5A6572",
      accent: "#047857",
      accentSoft: "#F0FDF4",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      headerBg: "#FFFFFF",
    },
    topAccentBar: true,
    pagePadding: "36px 42px",
    sectionSpacing: 18,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "education",
      "certifications",
      "projects",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  // ===== CATEGORY 2: MODERN PROFESSIONAL =====

  13: {
    // Template 13: Modern Rose Sidebar
    name: "Modern Rose Sidebar",
    layout: "two-column",
    headerLayout: "split",
    headingStyle: "bar",
    layoutType: "sidebar",
    headingVariant: "full-width-bar",
    typographyScale: 1.0,
    spacingScale: 1.0,
    fontFamily: "Inter, 'Source Sans Pro', sans-serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#E11D48",
      accentSoft: "#F8FAFC",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
      sidebarBg: "#F9F5F8",
      sidebarText: "#1F2937",
      sidebarMutedText: "#6B7280",
      sidebarBorder: "#F0E7ED",
      sidebarAccentSoft: "#E11D48",
    },
    sidebarWidth: "28%",
    sidebarSections: ["languages", "certifications", "skills", "strengths", "hobbies"],
    mainSections: [
      "summary",
      "experience",
      "education",
      "projects",
      "achievements",
      "custom",
    ],
    sidebarPadding: "24px 14px",
    sectionSpacing: 16,
    headerDivider: true,
  },

  // ===== CATEGORY 1: MINIMAL PROFESSIONAL =====

  14: {
    // Template 14: Minimal Classic Serif
    name: "Minimal Classic Serif",
    layout: "single",
    headerLayout: "stacked",
    headingStyle: "accent",
    layoutType: "single-column",
    headingVariant: "label-bar",
    typographyScale: 1.0,
    spacingScale: 1.0,
    fontFamily: "Merriweather, 'Georgia', serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#6B7280",
      accent: "#B45309",
      accentSoft: "#FFFBEB",
      accentText: "#FFFFFF",
      border: "#E5E7EB",
    },
    leftAccentLine: true,
    pagePadding: "36px 40px",
    sectionSpacing: 18,
    headerDivider: true,
    mainSections: [
      "summary",
      "skills",
      "experience",
      "education",
      "certifications",
      "projects",
      "achievements",
      "languages",
      "strengths",
      "hobbies",
      "custom",
    ],
  },

  // ===== CATEGORY 3: EXECUTIVE =====

  15: {
    // Template 15: Executive Heritage
    name: "Executive Heritage",
    layout: "two-column",
    headerLayout: "stacked",
    headingStyle: "bar",
    layoutType: "sidebar",
    headingVariant: "full-width-bar",
    typographyScale: 1.02,
    spacingScale: 1.02,
    fontFamily: "Georgia, 'Times New Roman', serif",
    palette: {
      page: "#FFFFFF",
      text: "#1F2937",
      mutedText: "#5A6572",
      accent: "#1E293B",
      accentSoft: "#F5F5F5",
      accentText: "#FFFFFF",
      border: "#D7DFE7",
      sidebarBg: "#1E293B",
      sidebarText: "#FFFFFF",
      sidebarMutedText: "#D1D5DB",
      sidebarBorder: "#374151",
      sidebarAccentSoft: "#374151",
    },
    sidebarWidth: "28%",
    sidebarSections: ["languages", "certifications", "skills", "strengths"],
    mainSections: [
      "summary",
      "experience",
      "education",
      "projects",
      "achievements",
      "custom",
    ],
    sidebarPadding: "24px 16px",
    sectionSpacing: 16,
    headerDivider: true,
    summaryStyle: "plain",
  },
};
